### PR TITLE
Feat/pupil 676/oak info button

### PR DESCRIPTION
**Pull request by benprotheroe**
# How to review this PR

_Leave this text block for the reviewer_

- Check [component hierarchy](https://miro.com/app/board/uXjVNnKBgyk=/?share_link_id=59445593794) is followed correctly
- Check the design [Heuristics](https://components.thenational.academy/?path=/docs/docs-howtodesigncomponents--docs#heuristics-for-component-design) have been followed
- Check [naming conventions](https://components.thenational.academy/?path=/docs/docs-namingconventions--docs) have been applied
- Check for these gotchyas:
  - Missing exports for Oak components
  - Accidental export of Internal components
  - Snapshots of unexpected components have been modified
  - Circular dependencies
  - Code duplication (via not using base components)
  - Non-functional storybook for this or related components
  - Sensitve files changed eg. atoms, or style tokens
  - Relative imports
  - Default exports

# Add your PR description below
create OakInfoButton in oak-compoent

## Link to the design doc
https://www.figma.com/file/zqpeecgzMGKRli2gUdJOLp/Pupil-Browse?type=design&node-id=4515%3A115907&mode=dev
## Testing instructions

go to storybook "components/organisms/pupil/OakQuizHint" 

### Acceptance criteria

- [ ]  open and closed states
- [ ]  other states

### CODE REVIEW

**Comment by messmike** [comment]
Also, the tooltip should align to the left of the icon button if possible e.g:
Screenshot 2024-05-02 at 2 12 28 pm

**Comment by RBrownsett** [comment]
@benprotheroe noticed that when viewing the tooltip info in mobile view the whole of the text is not viewable. Is there a way we could make this responsive to the screen size? 
image

**Comment by benprotheroe** [comment]
> @benprotheroe noticed that when viewing the tooltip info in mobile view the whole of the text is not viewable. Is there a way we could make this responsive to the screen size? image

i think it is rsponsive already; not sure why storybook makes it look weird, checkout: https://deploy-preview-156--lively-meringue-8ebd43.netlify.app/iframe.html?args=&id=components-organisms-pupil-oakinfobutton--default&viewMode=story

**Comment by RBrownsett** [comment]
> > @benprotheroe noticed that when viewing the tooltip info in mobile view the whole of the text is not viewable. Is there a way we could make this responsive to the screen size? image
> 
> i think it is rsponsive already; not sure why storybook makes it look weird, checkout: https://deploy-preview-156--lively-meringue-8ebd43.netlify.app/iframe.html?args=&id=components-organisms-pupil-oakinfobutton--default&viewMode=story

Ah you're right, looks like its a storybook issue with the text now showing correctly. I did try the link in browserstack on a real device, we do lose some padding at the top (first screenshot is Browserstack, the second is the link you sent above)

image

image

**Review by kimon-satan — CHANGES_REQUESTED** [review]
You've done this all in one component, but this is specifically not what the ticket asks for.  Can you follow the pattern of creating an OakInfo component which carries the tool tip functionality. This would be consistent with how OakQuizHint is implemented as well.

**Review by kimon-satan — APPROVED** [review]
nice

**Review by messmike — APPROVED** [review]
michael-rosen

**Pull request merged**
