### PR TITLE
PUPIL-585 Feat/pupil journey list item

### PR DESCRIPTION
**Pull request by benprotheroe**
# How to review this PR

_Leave this text block for the reviewer_

- Check [component hierarchy](https://miro.com/app/board/uXjVNnKBgyk=/?share_link_id=59445593794) is followed correctly
- Check the design [Heuristics](https://components.thenational.academy/?path=/docs/docs-howtodesigncomponents--docs#heuristics-for-component-design) have been followed
- Check [naming conventions](https://components.thenational.academy/?path=/docs/docs-namingconventions--docs) have been applied
- Check for these gotchyas:
  - Missing exports for Oak components
  - Accidental export of Internal components
  - Snapshots of unexpected components have been modified
  - Circular dependencies
  - Code duplication (via not using base components)
  - Non-functional storybook for this or related components
  - Sensitve files changed eg. atoms, or style tokens
  - Relative imports
  - Default exports

# Add your PR description below
This is the pupil journey list item to be used for lesson and unit listing pages
it has a disabled state when it is a div otherwise it is a a/button tag

## Link to the design doc

https://www.figma.com/file/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?type=design&node-id=8319%3A15791&mode=dev

## A link to the component in the deployment preview
[view component](https://deploy-preview-144--lively-meringue-8ebd43.netlify.app/?path=/docs/components-organisms-pupil-oakpupiljourneylistitem--docs)

## Testing instructions

go to above storybook link; and test styles, content and break points for various use cases

### CODE REVIEW

**Comment by messmike** [comment]
@benprotheroe just want to check if the pink container is a part of each individual list item, or will the list items be wrapped in a container that will add the margins, border radius, colour token?

**Comment by messmike** [comment]
Aside from my question above, here is my feedback for this component:
- For the mobile version, it looks like the number needs to be updated to use 'heading-5' 
- On mobile, can we use 'space-between-s' between the number/title and the link/icon? (looks a bit big when compared to the designs:

**Comment by rightsaidjames** [comment]
Issues found:
* When the component is a button, there is a redundant `href` attribute.
* There are no controls available in Storybook for this component, which makes it more difficult to test
* Design issues (especially on mobile), as noted above by Mike.
* The unavailable state has not been implemented, as noted by Mike.

Screenshot 2024-04-10 at 12 07 05

**Comment by messmike** [comment]
@benprotheroe thanks for the updates, comments here:
- I just saw the separate [ticket](https://www.notion.so/oaknationalacademy/InternalClickableListContainer-Component-64e8e1dab0a54253990e6eb158c7b378?pvs=4) for the OakListingPageLayout Component that's in progress, so that answers my [question](https://github.com/oaknational/oak-components/pull/144#issuecomment-2047239006) above, thanks.
- The unavailable variant just needs `bg-neutral` to be applied to the background colour, and `border-neutral-lighter` applied to the border, and `border-solid-m` for the border width:
Screenshot 2024-04-10 at 3 58 15 pm
- This may not be possible, but could we set a condition for when the title spans a new line so that the alignment is set to `start` for both mobile and desktop? Let me know if this wouldn't be possible to do. E.g:
Screenshot 2024-04-10 at 4 06 31 pm
- Will the optional lesson variant and the lock-up be part of another ticket? E.g: https://www.figma.com/file/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?type=design&node-id=8318%3A14897&mode=dev

**Comment by messmike** [comment]
> @messmike just checking, the positioning of the lesson number since alignment was updated. It now shows as below (screenshot of mobile view):
> 
> image

Hey @RBrownsett, I had a chant with @benprotheroe yesterday where went back and forth on trying different alignments. I proposed setting a condition to align the number and title to start when the title spans multiple lines, but Ben wasn't sure it was possible without doing a nasty hack to achieve it. E.g: 
screenshot_2024-04-11_at_10 23 16
We could change it to align at baseline, but I think when viewed in a list as they will appear in the product, it will look more balanced visually to keep it centre aligned. It does mean you get this for mobile with longer titles, but I think it will look better in more instances centre aligned. Unless we can extend the component in the future so it can behave as intended in the designs - which would be preferred.

**Review by RBrownsett — APPROVED** [review]
Happy with the colour update, now passes accessibility checks

**Comment by messmike** [comment]
A separate ticket has been added to extend the component that will support optional units: [](https://www.notion.so/oaknationalacademy/OakListingPageLayout-Component-extension-abc81e88c63d480babd97ae604ba40cb?pvs=4)

**Review by messmike — APPROVED** [review]

**Review by kimon-satan — APPROVED** [review]
Hole in one

**Pull request merged**
