### PR TITLE
Feat/pupil 891/oak quiz results

### PR DESCRIPTION
**Pull request by kimon-satan**
# How to review this PR

_Leave this text block for the reviewer_

- Check [component hierarchy](https://miro.com/app/board/uXjVNnKBgyk=/?share_link_id=59445593794) is followed correctly
- Check the design [Heuristics](https://components.thenational.academy/?path=/docs/docs-howtodesigncomponents--docs#heuristics-for-component-design) have been followed
- Check [naming conventions](https://components.thenational.academy/?path=/docs/docs-namingconventions--docs) have been applied
- Check for these gotchyas:
  - Missing exports for Oak components
  - Accidental export of Internal components
  - Snapshots of unexpected components have been modified
  - Circular dependencies
  - Code duplication (via not using base components)
  - Non-functional storybook for this or related components
  - Sensitve files changed eg. atoms, or style tokens
  - Relative imports
  - Default exports

# Add your PR description below

### Job Story

**When** I am rendering reviewing quiz results,
**I want to render the answers and grading**
**So that I can present the results to the user**.

This is the subcomponent which allows the results for each of the different answer types to be rendered.

## Link to the design doc

https://www.figma.com/design/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?m=auto&node-id=10477-21972

## A link to the component in the deployment preview

https://deploy-preview-249--lively-meringue-8ebd43.netlify.app/?path=/docs/components-organisms-pupil-internalquizresultitem--docs

## Testing instructions

try the different states and marvel

## ACs
- [x]  matches design
- [x]  storybook
- [x]  tests

### CODE REVIEW

**Comment by RBrownsett** [comment]
@kimon-satan Desktop view looking good, small issue with mobile view. 

I've taken one of the longer match questions from year 11 English and viewed via small mobile. The height of coloured background does not flex with the whole of the content text - also @messmike do we want the match answer and statement alongside each other in mobile view? See screenshot

image

**Comment by messmike** [comment]
> https://deploy-preview-249--lively-meringue-8ebd43.netlify.app/?path=/docs/components-organisms-pupil-internalquizresultitem--docs

Thanks @kimon-satan, looking good to me.

@RBrownsett for mobile I was thinking they could wrap. With them being separate fields, then having them stacked on top of one another on mobile might be better if that is an easy update to make in this ticket.

**Comment by kimon-satan** [comment]
@RBrownsett @messmike okay I've implemented the suggested mobile fix could you take another look and give me approval if okay. If this isn't right can I suggest we go for the change in a subsequent ticket with mobile views in the design docs as we're a bit blocked by this one.

**Comment by messmike** [comment]
> @RBrownsett @messmike okay I've implemented the suggested mobile fix could you take another look and give me approval if okay. If this isn't right can I suggest we go for the change in a subsequent ticket with mobile views in the design docs as we're a bit blocked by this one.

I think this works, nice one. Happy to approve - could update later for left-alignment as it looks centred now but I can spin up a small ticket for that.

**Review by messmike — APPROVED** [review]

**Review by RBrownsett — APPROVED** [review]
Approved - tested across different devices and control combinations. 

Follow on ticket will be made to amend alignment in mobile view if required by design.

**Comment by messmike** [comment]
Added a ticket for the alignment to the next sprint backlog: [https://www.notion.so/oaknationalacademy/OakQuizResultItem-left-align-25704b8d019748f4b5314b85b7bc6008?pvs=4](https://www.notion.so/oaknationalacademy/OakQuizResultItem-left-align-25704b8d019748f4b5314b85b7bc6008?pvs=4)

**Pull request merged**
