### PR TITLE
PUPIL-709 Feat/optionality item component

### PR DESCRIPTION
**Pull request by benprotheroe**
# How to review this PR

_Leave this text block for the reviewer_

- Check [component hierarchy](https://miro.com/app/board/uXjVNnKBgyk=/?share_link_id=59445593794) is followed correctly
- Check the design [Heuristics](https://components.thenational.academy/?path=/docs/docs-howtodesigncomponents--docs#heuristics-for-component-design) have been followed
- Check [naming conventions](https://components.thenational.academy/?path=/docs/docs-namingconventions--docs) have been applied
- Check for these gotchyas:
  - Missing exports for Oak components
  - Accidental export of Internal components
  - Snapshots of unexpected components have been modified
  - Circular dependencies
  - Code duplication (via not using base components)
  - Non-functional storybook for this or related components
  - Sensitve files changed eg. atoms, or style tokens
  - Relative imports
  - Default exports

go to [storybook](https://deploy-preview-184--lively-meringue-8ebd43.netlify.app/?path=/docs/components-organisms-pupil-oakpupiljourneyoptionalityitem--docs)
  
### Job Story

**When** a unit has optionality,
**I want a list component which handles the optionality**
**So that users can navigate to the optional units**

### Implementation details

https://www.figma.com/design/YcWQMMhHPVVmc47cHHEEAl/%F0%9F%9F%A2-Oak-Design-Kit?m=auto&node-id=8322%3A17111

https://www.figma.com/design/zqpeecgzMGKRli2gUdJOLp/Pupil-Browse?m=dev&node-id=4285%3A42847

https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fdesign%2FzqpeecgzMGKRli2gUdJOLp%2FPupil-Browse%3Fm%3Ddev%26node-id%3D4285%253A42847

### Acceptance criteria

- [x]  A dedicated component
- [x]  prop accepts an array of of unit objects comprising title, href, num lessons (and order ?)
- [x]  other props are the same as the pupilJourneyLessonListingItem
- [x]  hover and focus states
- [x]  stories for up to (5 options ?)

### CODE REVIEW

**Comment by messmike** [comment]
@benprotheroe can you pop a link in to review?

**Comment by messmike** [comment]
@benprotheroe just one thing from me:

- On mobile, the Optional lesson item title looks a bit small, it should use `heading-7` e.g:
Screenshot 2024-05-20 at 10 47 28 am

**Review by RBrownsett — APPROVED** [review]
Approved - testing details added to ticket. Will need to check contrast when deployed, but manually checked with no issues.

**Review by BTitterington — APPROVED** [review]
Looks good.

**Review by messmike — APPROVED** [review]

**Pull request merged**
