### PR TITLE
LESQ-888: OakUnitListItem Component

### PR DESCRIPTION
**Pull request by k-huggs**
# How to review this PR

_Leave this text block for the reviewer_

- Check [component hierarchy](https://miro.com/app/board/uXjVNnKBgyk=/?share_link_id=59445593794) is followed correctly
- Check the design [Heuristics](https://components.thenational.academy/?path=/docs/docs-howtodesigncomponents--docs#heuristics-for-component-design) have been followed
- Check [naming conventions](https://components.thenational.academy/?path=/docs/docs-namingconventions--docs) have been applied
- Check for these gotchyas:
  - Missing exports for Oak components
  - Accidental export of Internal components
  - Snapshots of unexpected components have been modified
  - Circular dependencies
  - Code duplication (via not using base components)
  - Non-functional storybook for this or related components
  - Sensitve files changed eg. atoms, or style tokens
  - Relative imports
  - Default exports

# Add your PR description below

Refactored Unit List Item Component, created within the components lib and storybook

## Link to the design doc

https://www.figma.com/design/YcWQMMhHPVVmc47cHHEEAl/%F0%9F%9F%A2-Oak-Design-Kit?m=dev

## A link to the component in the deployment preview

https://deploy-preview-209--lively-meringue-8ebd43.netlify.app/?path=/docs/components-organisms-teacher-oakunitlistitem--docs

## Testing instructions

Navigate to the storybook link to test the design at different states and on different view ports

## ACs

Build new Unit List Item component with corresponding states denoted in Figma designs

### CODE REVIEW

**Review by njblore — APPROVED** [review]

**Review by jack-skerrett-oak — COMMENTED** [review]
I know you didn't ask for my review but I have snuck in :P What is this unavailable value and why does it add a black border around the card?

**Comment by k-huggs** [comment]
> I know you didn't ask for my review but I have snuck in :P What is this unavailable value and why does it add a black border around the card?

Removed the border. Presumed if any units were expired or not released yet they would be unavailable

**Review by Monika-Koziol — CHANGES_REQUESTED** [review]
A few changes from me:

- [x] the padding around the white box meant to be 20px all around (padding: var(--Tokens-Inner-Padding-inner-padding-l, 20px); 

- [ ] component has a white top and bottom margin that gets even bigger on mobile. Can this be removed?

- [ ] the hover state has a slight interaction: 
animation-timing-function: ease-out;
animation-duration: 300ms;

- [ ] The spacing between lesson title / year / number of lessons seems uneven. Can we increase the gap between years and lesson number?
Would it be possible to see how this space looks when there are a few of those components with various title lengths? 

- [ ] is there a legacy variant that has a slightly higher blue background for the number? 
- [ ] disabled state: white background should change to background: var(--Tokens-Background-bg-neutral, #F2F2F2);

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
[ ] Unfortunately looks like small (and large) mobile views in Storybook bleed over the edge. 
Screenshot 2024-06-26 at 15 24 51

I'll trust Monika on all the colours and spacings!

**Review by Monika-Koziol — CHANGES_REQUESTED** [review]
- [ ] Some strange indentation is happening with titles on mobile, see screenshot. 

The padding all seemed to work fine now.

**Comment by k-huggs** [comment]
> [ ] Unfortunately looks like small (and large) mobile views in Storybook bleed over the edge. Screenshot 2024-06-26 at 15 24 51
> 


> I'll trust Monika on all the colours and spacings!

Fixed the overflow bug @Monika-Koziol would it be possible to check the alignment on the small phone view? 

Screenshot 2024-06-26 at 15 56 57

**Review by Monika-Koziol — APPROVED** [review]

**Review by jack-skerrett-oak — APPROVED** [review]
This was behaving weirdly for me, and only me so we are merging and will see how it works once on the site.

**Comment by k-huggs** [comment]
> This was behaving weirdly for me, and only me so we are merging and will see how it works once on the site.

Should be fixed now 

https://github.com/oaknational/oak-components/assets/91190841/4ac6ff66-6d5c-4d0d-bba7-9f1b08cf507e

**Pull request merged**
