### PR TITLE
[PUPIL-838] Add OakInlineBanner component and tests

### PR DESCRIPTION
**Pull request by BTitterington**
# How to review this PR

_Leave this text block for the reviewer_

- Check [component hierarchy](https://miro.com/app/board/uXjVNnKBgyk=/?share_link_id=59445593794) is followed correctly
- Check the design [Heuristics](https://components.thenational.academy/?path=/docs/docs-howtodesigncomponents--docs#heuristics-for-component-design) have been followed
- Check [naming conventions](https://components.thenational.academy/?path=/docs/docs-namingconventions--docs) have been applied
- Check for these gotchyas:
  - Missing exports for Oak components
  - Accidental export of Internal components
  - Snapshots of unexpected components have been modified
  - Circular dependencies
  - Code duplication (via not using base components)
  - Non-functional storybook for this or related components
  - Sensitve files changed eg. atoms, or style tokens
  - Relative imports
  - Default exports

# Add your PR description below

Added new OakInlineBanner. It has 5 types - info, neutral, success, alert, error
It can also be overridden to change the icon and colours etc.

## Link to the design doc

https://www.figma.com/design/YcWQMMhHPVVmc47cHHEEAl/%F0%9F%9F%A2-Oak-Design-Kit?node-id=9923-4249&m=dev

## A link to the component in the deployment preview

https://deploy-preview-222--lively-meringue-8ebd43.netlify.app/?path=/docs/components-molecules-oakinlinebanner--docs

## Testing instructions

Check the component is displayed and works as expected on desktop and mobile devices
Check accessibility of the component

### CODE REVIEW

**Comment by RBrownsett** [comment]
@BTitterington looking good - just want to check - for all of the banners labelled up 'simple' they show the link and dismiss button alongside the text rather than below - is that correct? Or should the link and the dismiss button be in the corners of the banner? 

image

image

**Comment by BTitterington** [comment]
@RBrownsett I just went off the design doc, although there was no mobile view that I could find (which does seem to make them look a little less appealing). Mike did take a quick look at them on Thursday and didn't spot anything other than an incorrect colour.

**Review by RBrownsett — APPROVED** [review]
Approved - tested in mobile and across different browsers

**Comment by BTitterington** [comment]
@kimon-satan - related to our conversation earlier, I'm not sure if you think this should be an organism or molecule, happy to move it to organism if you think it's more appropriate there.

**Review by kimon-satan — APPROVED** [review]
Very nice

**Pull request merged**
